### ISSUE TITLE
zero-dependency pydust

### ISSUE THREAD

**Issue by shakfu** [spiraldb/ziggy-pydust#161]
While playing around with pydust in my recent [PR](https://github.com/fulcrum-so/ziggy-pydust/pull/158), I was thinking about whether it would be possible to reduce pydust's dependencies to zero (outside of python and a zig compiler in PATH):

Pydust's current dependencies are as follows (please correct me if I'm wrong here):

1. `ziglang`:  pip installable `zig` compiler (redundant if zig compiler is in your system PATH)
2. `setuptools`: presumably required for the pyproject.toml build system integration
3. `black`: provides stub generation:  eg `fib.pyi`, ..
4. `pydantic`: provides type-checking, serialization / deserialization and more (`dataclasses` on steroids)

If one has an objective of making a zero-dependency `pydust` variant, one could consider dropping `ziglang`  and `setuptools` and make stub_generation optionally available only if `black` is installed. As for the use of `pydantic`, it's only used in the two config classes: `config.ExtModule` and `config.ToolPydust` and could conceivably be dropped for some stdlib-only-dependent code (`dataclasses`?) .

While it is debatable why one would want a zero-dependency project, could this be considered as an objective by the project owners? Or are the above dependencies strategically important for the project's roadmap?

**Comment by gatesn** [comment]
Unless there's a clear use-case, I'm not sure I see the benefit of removing the dependencies?

Regarding ziglang in particular, it's desirable to ensure source distributions can compile themselves during install _without_ any external dependencies on the user's machine (i.e. a Zig toolchain). We see this as a huge benefit over shipping native C extensions. This could also be achieved by having Pydust users add `zig lang` to their build-system.requires instead of pydust taking the dependency, so this one is up for debate (particularly given how heavy it is)

**Comment by shakfu** [comment]
> Unless there's a clear use-case, I'm not sure I see the benefit of removing the dependencies?

Fair enough. 

> Regarding ziglang in particular, it's desirable to ensure source distributions can compile themselves during install _without_ any external dependencies on the user's machine (i.e. a Zig toolchain). We see this as a huge benefit over shipping native C extensions. This could also be achieved by having Pydust users add `zig lang` to their build-system.requires instead of pydust taking the dependency, so this one is up for debate (particularly given how heavy it is)

Thanks. I understand the logic now, and I agree regarding 'ziglang', as it's currently downloaded and installed even if one wants to use one's system zig.
